# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('optiona', models.TextField()),
                ('optionb', models.TextField()),
                ('optionc', models.TextField()),
                ('optiond', models.TextField()),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
