# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 04:54
from __future__ import unicode_literals

from django.db import migrations

#def create_initial_questions(apps, schema_editor):
#    Question = apps.get_model('restapp', 'Question')
#    
#    Question(text='what is your name?', optiona='zahid', optionb='shahid', optionc='isna', optiond='inayat', answer='shahid').save()
#    Question(text='what is your age?', optiona='25', optionb='27', optionc='28', optiond='29', answer='27').save()
#    Question(text='where do you live?', optiona='shopian', optionb='budgam', optionc='srinagar', optiond='pulwama', answer='shopian').save()
#    Question(text='what is your profession?', optiona='Teacher', optionb='carpenter', optionc='engineer', optiond='doctor', answer='engineer').save()
#    Question(text='what is your religion?', optiona='christianity', optionb='buddhism', optionc='islam', optiond='jewism', answer='islam').save()
#    Question(text='what is your favourite programming language?', optiona='java', optionb='python', optionc='javascript',optiond='none',answer='python').save()
#





class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
     
    ]
