# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20180223_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='optiona',
            new_name='answera',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='optionb',
            new_name='answerb',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='optionc',
            new_name='answerc',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='optiond',
            new_name='answerd',
        ),
    ]
