# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20180223_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='answer', to='restapp.Answer'),
        ),
        migrations.AlterField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='restapp.Question'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sections',
            field=models.ManyToManyField(related_name='section', to='restapp.Section'),
        ),
    ]
