# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20180223_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='answers', to='restapp.Answer'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sections',
            field=models.ManyToManyField(related_name='sections', to='restapp.Section'),
        ),
    ]
