# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_auto_20180223_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='a',
            field=models.CharField(default='option one', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='b',
            field=models.CharField(default='option two', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='c',
            field=models.CharField(default='option three', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='d',
            field=models.CharField(default='option four', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='option five', max_length=40),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='section title', max_length=40),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='subject title', max_length=40),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
