# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_auto_20180223_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sections',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('HIST', 'History'), ('GEOG', 'Geography'), ('POLI', 'Polity'), ('SCIE', 'Science'), ('ECON', 'Economics'), ('GENK', 'Gk'), ('ECOL', 'Ecology')], default='HIST', max_length=15),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
